### ISSUE TITLE
Reproducing of TAD

### ISSUE THREAD

**Issue by gyusik19** [OpenGVLab/VideoMAEv2#1]
Awesome Work!
Do you have plans for sharing the reproduction of  Temporal Action Detection Task?

**Comment by congee524** [comment]
Hello!
For the TAD task, we use a two-stage approach: after extracting features with VideoMAE V2-g, we trained using the [ActionFormer codebase](https://github.com/happyharrycn/actionformer_release) without making any modifications to the method. In the next few days, we will release the features of THUMOS’14 and FineAction extracted by VideoMAE V2-g. Please stay tuned for updates.

**Comment by gyusik19** [comment]
Thank you very much for your reply!!
will VideoMAE V2-g model also be available for extracting features of my own dataset?

**Comment by congee524** [comment]
> 

Yes! We will also release the giant model :p

**Comment by gyusik19** [comment]
Thank you for your reply :)

**Comment by congee524** [comment]
> Thank you for your reply :)

Giant model is available :-D

**Comment by Value-Jack** [comment]
if possible，could you please extract the  features of ActivityNet1.2  extracted by VideoMAE V2-g and share it in the future?  thank you very much!
