### ISSUE TITLE
Could you provide the "misc/label_710to710.json" file?

### ISSUE THREAD

**Issue by yerx** [OpenGVLab/VideoMAEv2#26]
For the data_set 'Kinetics-710', the file "label_710to710.json" is required, but I can't find it in the "misc" directory. Could you please provide the file? Thanks.

**Comment by congee524** [comment]
This file is unnecessary, we don't need to turn K710 head to K710 head 😂. If you want to see how the labels correspond, you could look at the `label_map_k710.txt`.
