### ISSUE TITLE
In datasets/build.py > def build_dataset > should the "anno_path" for mode = 'test' be (args.data_path, 'test.csv') instead of what it is currently (args.data_path, 'val.csv')?

### ISSUE THREAD

**Issue by yerx** [OpenGVLab/VideoMAEv2#27]
`def build_dataset(is_train, test_mode, args):
    if is_train:
        mode = 'train'
        anno_path = os.path.join(args.data_path, 'train.csv')
    elif test_mode:
        mode = 'test'
        anno_path = os.path.join(args.data_path, 'val.csv')
    else:
        mode = 'validation'
        anno_path = os.path.join(args.data_path, 'val.csv')`

**Comment by congee524** [comment]
Yes, but generally we use the validation set, and often only at competition will there be additional test datasets. Feel free to change the name of it to what you want.
