### ISSUE TITLE
How to train my own dataset?

### ISSUE THREAD

**Issue by wang9danzuishuai** [OpenGVLab/VideoMAEv2#30]
I want to do some experiments on my own dataset, using the fine-tuning method.
But in the training script, the param 'data_set' only contains some open datasets.
My dataset only has 10 classes. If I changed the --nb_class to 10, an AssertionERROR will raise.
After skipping this assertion, my dataset starts to train but the ACC@1 is always 0%.
So is there something that I should do correctly train my own dataset?

**Comment by wang9danzuishuai** [comment]
Sorry to bother you, I have found the way:)

**Comment by Muhammad-k02** [comment]
> Sorry to bother you, I have found the way:)

Do you mind elaborating on how you got your custom dataset trained?

**Comment by Wu-Lei1** [comment]
> Sorry to bother you, I have found the way:)

hello, how is the fine-tuning result on your custom dataset? I have fine-tuned videomaev2 based on ViT-S with my data, but the results is always 0~50%.
