### ISSUE TITLE
Request for the training script for VideoMAE-V2-Base

### ISSUE THREAD

**Issue by qinghuannn** [OpenGVLab/VideoMAEv2#34]
Hi. Thanks for your nice work! I need to train VideoMAE-V2-Base on the Kinetics-400 dataset, but I didn't find the training script for VideoMAE-V2-Base. And I didn't find the performance of VideoMAE-V2-Base on the Kinectics-400 dataset in your paper. Could you tell me the performance of VideoMAE-V2-Base on the Kinectics-400 dataset?

**Comment by Jin-Chow** [comment]
Hello @qinghuannn ，have you successfully run the code，I have met some trouble，I would appreciate it if you can help me！

**Comment by qinghuannn** [comment]
No. I haven’t run the code since I didn’t find the  training script for Video-MAE-V2. You can post your questions on this repo, the authors will help you.在 2023年8月5日，14:08，Jin-Chow ***@***.***> 写道：﻿
Hello @qinghuannn ，have you successfully run the code，I have met some trouble，I would appreciate it if you can help me！

**Comment by congee524** [comment]
Thanks for your attention. To train vit model with VideoMAE V2 method on K400, you only need to modify the dataset root of training script.
