### ISSUE TITLE
Apply for the model weight of 'vit_g_hybrid_pt_1200e_k710_it_k400_ft'

### ISSUE THREAD

**Issue by jinyucn** [OpenGVLab/VideoMAEv2#35]
Hello, from the download link, I can only find the model weight fine-tuned with 'vit_g_hybrid_pt_1200e_k710_ft' and 'vit_g_hybrid_pt_1200e_ssv2_ft'. Could you provide me with the model fine-tuned on kinetics400, i.e., 'vit_g_hybrid_pt_1200e_k710_it_k400_ft'. My email is jychencs@gmail.com. Thank you.

**Comment by congee524** [comment]
Sorry, it's been so long that I couldn't find the checkpoint, but this only requires 1~3 epochs of training, so the resource overhead shouldn't be particularly high.
