### ISSUE TITLE
Visualization Script

### ISSUE THREAD

**Issue by kfirgoldberg** [OpenGVLab/VideoMAEv2#36]
Hi,
thanks for the great repo!
Can you please publish code for the visualization of the predicted completions for a video?

Thanks,
Kfir

**Comment by congee524** [comment]
you could refer to [run_videomae_vis.py](https://github.com/MCG-NJU/VideoMAE/blob/main/run_videomae_vis.py)

**Comment by fengjingchehu** [comment]
> 嗨，感谢您的精彩回购！您能否发布用于可视化视频预测完成度的代码？
> 
> 谢谢，克菲尔

i wonder have u ever make it ?
