### ISSUE TITLE
Pretrained smaller models availability

### ISSUE THREAD

**Issue by ganzobtn** [OpenGVLab/VideoMAEv2#45]
Hello. Thank you for the great work. 
            1. Could you provide me with the ViT-B adn ViT-S model? 
            2. How much GPU VRAM required when I fine-tune pretrained ViT-G model on custom video dataset? When I try to finetune it with batch size of 1 on V100 with 32GB memory, it is showing CUDA out of memory error. Is there sth wrong with what I am doing?

**Comment by congee524** [comment]
1. [vit_b_hybrid_pt_800e.pth](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/internvideo/pretrain/videomae/vit_b_hybrid_pt_800e.pth)
2. we fine-tune vit-g with batch_size=6 on 80G-A100. Kindly check your pytorch version (the higher, the better) or you could use checkpointing.

hope it helps.

**Comment by mayarkamali** [comment]
Hello, thank you for your work, 

could you please provide again the ViT-B adn ViT-S model, the shared link does not work anymore.

Thank you in advance

**Comment by nomaad42** [comment]
@ganzobtn @congee524 , could you please share this vit_b_hybrid_pt_800e.pth?

**Comment by K1NSA** [comment]
Could you please share the vit_b_hybrid_pt8003.pth? It seems the link is broken. @congee524 @ganzobtn

**Comment by congee524** [comment]
The complete collection of VideoMAE V2 models is available here: https://huggingface.co/collections/OpenGVLab/videomae-v2
