### ISSUE TITLE
The feature details of THUMOS14 dataset. 

### ISSUE THREAD

**Issue by dingfengshi** [OpenGVLab/VideoMAEv2#5]
Hi! Thanks for your excellent work! Could you please give me some details about the feature extraction of the THUMOS14 dataset (eg. FPS of videos, the number of frames in each clip, the stride)?  Is the feature a fixed length or is it a different length for each video? Thank you very much!

**Comment by congee524** [comment]
Hello~ We will release the code for feature extraction in the next two days (and may also release the extracted features in the next week). hope this can be helpful to you.

**Comment by dingfengshi** [comment]
OK, thank you very much.
