### ISSUE TITLE
Where to find the script of finetuning on 'Temporal action detection' task?

### ISSUE THREAD

**Issue by Leo-Yuyang** [OpenGVLab/VideoMAEv2#51]
Thank you for your amazing work. I was trying to use VideoMAEv2 to do a temporal action detection task. But I can't find the detailed implementation related to this task. Could you please give me some advice?

**Comment by congee524** [comment]
https://github.com/OpenGVLab/VideoMAEv2/blob/master/docs/TAD.md

you could refer to the above doc. we use actionformer codebase with offline extracted videomae v2 features.

**Comment by Leo-Yuyang** [comment]
Thank you for your prompt response! I was just about to send you this email, lol:
![49d20e1b25627c28d3abf5c2cc1d1d36](https://github.com/OpenGVLab/VideoMAEv2/assets/53007066/f05bb35c-5089-4f22-b37e-a5a02c9ecfaf)
Anyway, I have learned how to extract features using videomae v2. However, this link below is so general and not specific enough:

**Comment by congee524** [comment]
This part of the experiment was not done by me, and I'm not sure of the exact details. But I think you could try to figure out the framework code of action former (it should be an important work in tad), or you could ask for help from other people who mentioned in other issues that they were working on tad tasks.

**Comment by Leo-Yuyang** [comment]
Thank you for your explanation and work!

**Comment by myccver** [comment]
> Thank you for your prompt response! I was just about to send you this email, lol: ![49d20e1b25627c28d3abf5c2cc1d1d36](https://private-user-images.githubusercontent.com/53007066/293928737-f05bb35c-5089-4f22-b37e-a5a02c9ecfaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDEyNDcsIm5iZiI6MTcxNTYwMDk0NywicGF0aCI6Ii81MzAwNzA2Ni8yOTM5Mjg3MzctZjA1YmIzNWMtNTA4OS00ZjIyLWIzN2UtYTVhMDJjOWVjZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExNDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYWU3ZDI4MDFmNWE5N2UxZDU5MmExZTdmMDQyNWI1MzY2NDE1YTM1ZTM3ZTVhNjAyMzBlMmZmODMwNTZhZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3eUiguT2lOPeAcHnAyfiXbDgwp6NBtQwEatLsLNNpL4) Anyway, I have learned how to extract features using videomae v2. However, this link below is so general and not specific enough: ![image](https://private-user-images.githubusercontent.com/53007066/293929107-765f5f08-007a-4085-87a1-de23c82b8ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDEyNDcsIm5iZiI6MTcxNTYwMDk0NywicGF0aCI6Ii81MzAwNzA2Ni8yOTM5MjkxMDctNzY1ZjVmMDgtMDA3YS00MDg1LTg3YTEtZGUyM2M4MmI4YWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExNDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYWJjNTFkNjgyZDQzZjdjOTIxZTk2ODkwM2Q0N2NlYWMyNGY3OTljZjYxMDQzMDM2ZDQ0MjJkYmUzYmFhYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3AUUuQYSh5wy1WLtdKwPRoBMq6vzy3BzwogWSrryGWc) Could you please give me more guidance? For example, after possessing the extracted features, which script in Actionformer should I refer or use to do the next inference step? Thank you for your support!



> Thank you for your prompt response! I was just about to send you this email, lol: ![49d20e1b25627c28d3abf5c2cc1d1d36](https://private-user-images.githubusercontent.com/53007066/293928737-f05bb35c-5089-4f22-b37e-a5a02c9ecfaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDEyNDcsIm5iZiI6MTcxNTYwMDk0NywicGF0aCI6Ii81MzAwNzA2Ni8yOTM5Mjg3MzctZjA1YmIzNWMtNTA4OS00ZjIyLWIzN2UtYTVhMDJjOWVjZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExNDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYWU3ZDI4MDFmNWE5N2UxZDU5MmExZTdmMDQyNWI1MzY2NDE1YTM1ZTM3ZTVhNjAyMzBlMmZmODMwNTZhZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3eUiguT2lOPeAcHnAyfiXbDgwp6NBtQwEatLsLNNpL4) Anyway, I have learned how to extract features using videomae v2. However, this link below is so general and not specific enough: ![image](https://private-user-images.githubusercontent.com/53007066/293929107-765f5f08-007a-4085-87a1-de23c82b8ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDEyNDcsIm5iZiI6MTcxNTYwMDk0NywicGF0aCI6Ii81MzAwNzA2Ni8yOTM5MjkxMDctNzY1ZjVmMDgtMDA3YS00MDg1LTg3YTEtZGUyM2M4MmI4YWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExNDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYWJjNTFkNjgyZDQzZjdjOTIxZTk2ODkwM2Q0N2NlYWMyNGY3OTljZjYxMDQzMDM2ZDQ0MjJkYmUzYmFhYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3AUUuQYSh5wy1WLtdKwPRoBMq6vzy3BzwogWSrryGWc) Could you please give me more guidance? For example, after possessing the extracted features, which script in Actionformer should I refer or use to do the next inference step? Thank you for your support!



> Thank you for your prompt response! I was just about to send you this email, lol: ![49d20e1b25627c28d3abf5c2cc1d1d36](https://private-user-images.githubusercontent.com/53007066/293928737-f05bb35c-5089-4f22-b37e-a5a02c9ecfaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDEyNDcsIm5iZiI6MTcxNTYwMDk0NywicGF0aCI6Ii81MzAwNzA2Ni8yOTM5Mjg3MzctZjA1YmIzNWMtNTA4OS00ZjIyLWIzN2UtYTVhMDJjOWVjZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExNDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYWU3ZDI4MDFmNWE5N2UxZDU5MmExZTdmMDQyNWI1MzY2NDE1YTM1ZTM3ZTVhNjAyMzBlMmZmODMwNTZhZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3eUiguT2lOPeAcHnAyfiXbDgwp6NBtQwEatLsLNNpL4) Anyway, I have learned how to extract features using videomae v2. However, this link below is so general and not specific enough: ![image](https://private-user-images.githubusercontent.com/53007066/293929107-765f5f08-007a-4085-87a1-de23c82b8ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDEyNDcsIm5iZiI6MTcxNTYwMDk0NywicGF0aCI6Ii81MzAwNzA2Ni8yOTM5MjkxMDctNzY1ZjVmMDgtMDA3YS00MDg1LTg3YTEtZGUyM2M4MmI4YWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExNDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYWJjNTFkNjgyZDQzZjdjOTIxZTk2ODkwM2Q0N2NlYWMyNGY3OTljZjYxMDQzMDM2ZDQ0MjJkYmUzYmFhYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3AUUuQYSh5wy1WLtdKwPRoBMq6vzy3BzwogWSrryGWc) Could you please give me more guidance? For example, after possessing the extracted features, which script in Actionformer should I refer or use to do the next inference step? Thank you for your support!

你好，请问你用代码可以成功提取特征吗？

**Comment by nomaad42** [comment]
@Leo-Yuyang , have you figured out ? If yes, can you please share
