### ISSUE TITLE
What should I do if I want to get the features of ActivityNet-1.3?

### ISSUE THREAD

**Issue by hongminglin08** [OpenGVLab/VideoMAEv2#52]

**Comment by congee524** [comment]
you could modify [extract_tad_feature.py](https://github.com/OpenGVLab/VideoMAEv2/blob/master/extract_tad_feature.py) to extract the featuress by yourself.

**Comment by Demo202111** [comment]
您好！请问extract_tad_feature.py文件中的 --model参数应该填什么？是保持默认值就可以吗

**Comment by congee524** [comment]
> 您好！请问extract_tad_feature.py文件中的 --model参数应该填什么？是保持默认值就可以吗

这个要和你用的 checkpoint 对应。填写的默认值对应 vit-g model 提特征

**Comment by Demo202111** [comment]
> > 您好！请问extract_tad_feature.py文件中的 --model参数应该填什么？是保持默认值就可以吗
> 
> 这个要和你用的 checkpoint 对应。填写的默认值对应 vit-g model 提特征
、
您好还有一个遗留问题vit-g model应该如何获取，可以通过scripts/pretrain/vit_g_hybrid_pt.sh训练得来吗，还是您有提供训练好的版本。如果要通过训练得来vit_g_hybrid_pt.sh中的DATA_PATH参数应该填写数据集路径吗？ 十分感谢您对领域发展做出的巨大贡献

**Comment by congee524** [comment]
从 model zoo 里面找，一般用 k710 上 finetune 过的模型来提特征

https://github.com/OpenGVLab/VideoMAEv2/blob/master/docs/MODEL_ZOO.md

**Comment by Demo202111** [comment]
> 从 model zoo 里面找，一般用 k710 上 finetune 过的模型来提特征
> 
> https://github.com/OpenGVLab/VideoMAEv2/blob/master/docs/MODEL_ZOO.md
好的！感谢您的回复
