### ISSUE TITLE
Model Weights

### ISSUE THREAD

**Issue by SamHSHS** [OpenGVLab/VideoMAEv2#63]
Thank you for sharing your work. 
I've tried to download the models stored in the server: https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/internvideo/distill/
It seems that they are not available anymore. Would it be possible to have it stored on google drive, or another location?

Thank you.

**Comment by congee524** [comment]
Sorry, due to technical issues, the model is temporarily unavailable for download. We expect this to be resolved within a few weeks.

**Comment by puren** [comment]
hello! is it possible to put them in some kinds of drive such as Google drive? I was in the middle of a project and unfortunately didn't saved the model weights considering I would have access later. I don't have resources to train it from scratch. It would be very helpful if you can provide them.

**Comment by congee524** [comment]
> hello! is it possible to put them in some kinds of drive such as Google drive? I was in the middle of a project and unfortunately didn't saved the model weights considering I would have access later. I don't have resources to train it from scratch. It would be very helpful if you can provide them.

Unfortunately, I no longer have access to the model weights since I left my previous job. My former colleague is currently working on resolving this issue. It appears that the frequent downloads led to us running out of the bandwidth quota.

**Comment by puren** [comment]
thank you for your reply!

**Comment by congee524** [comment]
Upload the weights to hugging face. Have updated the link in the model link sheet
