### ISSUE TITLE
The model download link is broken

### ISSUE THREAD

**Issue by Bazinga699** [OpenGVLab/VideoMAEv2#64]
Great work!!

Unfortunately, the link is broken:[vit_b_k710_dl_from_giant.pth](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/internvideo/distill/vit_b_k710_dl_from_giant.pth). 

I really want to try your model and do some interesting work, hope you can fix it.
Thanks

**Comment by yinanhe** [comment]
Thank you for pointing that out. Checkpoints have been migrated to HuggingFace. You can obtain them via [VideoMAEv2-S](https://huggingface.co/OpenGVLab/VideoMAE2/resolve/main/distill/vit_s_k710_dl_from_giant.pth) and [VideoMAEv2-B](https://huggingface.co/OpenGVLab/VideoMAE2/resolve/main/distill/vit_b_k710_dl_from_giant.pth).

**Comment by congee524** [comment]
Thank you yinan :)
I have updated the link in the model zoo file.
