### ISSUE TITLE
Checkpoint link broken

### ISSUE THREAD

**Issue by hamzakhalil798** [OpenGVLab/VideoMAEv2#67]
Please fix vit b and vit s checkpoint links.

**Comment by yinanhe** [comment]
Hi, Thank you for pointing that out. Checkpoints have been migrated to Hugging Face. You can obtain them via [VideoMAEv2-S](https://huggingface.co/OpenGVLab/VideoMAE2/resolve/main/distill/vit_s_k710_dl_from_giant.pth) and [VideoMAEv2-B](https://huggingface.co/OpenGVLab/VideoMAE2/resolve/main/distill/vit_b_k710_dl_from_giant.pth)

**Comment by hamzakhalil798** [comment]
Thankyou so much!
