### ISSUE TITLE
The TAD Features download link is broken

### ISSUE THREAD

**Issue by LHX0303** [OpenGVLab/VideoMAEv2#69]
Great work!!

Unfortunately, the link is broken: [th14_mae_g_16_4.tar.gz](https://pjlab-gvm-data.oss-cn-shanghai.aliyuncs.com/internvideo/features/th14_mae_g_16_4.tar.gz).

I really want to try your model and do some interesting work, hope you can fix it.
Thanks

**Comment by congee524** [comment]
@yinanhe Hi Yinan, Do you still keep the backup file? Could you help to upload it to hf? Sorry to trouble you ...

**Comment by yinanhe** [comment]
Sure!  I have uploaded the corresponding feature files to Hugging Face. @LHX0303 You can find them at [huggingface](https://huggingface.co/datasets/OpenGVLab/VideoMAEv2-TAL-Features/tree/main). If it's convenient, please @congee524 update the link?

**Comment by congee524** [comment]
Big thanks @yinanhe ! I will update it.

**Comment by LHX0303** [comment]
Big thanks！^_^ @yinanhe @congee524
