### ISSUE TITLE
TAD timm版本

### ISSUE THREAD

**Issue by yubo200526** [OpenGVLab/VideoMAEv2#72]
您好，在您提供的requirments.txt中timm版本是0.4.12，但这个版本的timm并没有提供对应的vit_giant_patch14_224模型，而在高版本的timm中无法正常使用任何vit_*模型

**Comment by congee524** [comment]
定义在这里https://github.com/OpenGVLab/VideoMAEv2/blob/29eab1e8a588d1b3ec0cdec7b03a86cca491b74b/models/modeling_finetune.py#L518-L529

**Comment by yubo200526** [comment]
> 定义在这里
> 
> https://github.com/OpenGVLab/VideoMAEv2/blob/29eab1e8a588d1b3ec0cdec7b03a86cca491b74b/models/modeling_finetune.py#L518-L529

这里如果使用timm=0.4.12版本会报错![image](https://github.com/user-attachments/assets/2509a375-b44b-47fd-85c2-1163fe137b7b)

**Comment by yubo200526** [comment]
> 定义在这里
> 
> https://github.com/OpenGVLab/VideoMAEv2/blob/29eab1e8a588d1b3ec0cdec7b03a86cca491b74b/models/modeling_finetune.py#L518-L529

如果使用timm=1.0.11版本会报错![image](https://github.com/user-attachments/assets/402dc625-9e84-4225-8f2e-41e4a62a2539)

**Comment by yubo200526** [comment]
已解决，高版本timm需要注释部分参数
